### ISSUE TITLE
Old archive files, for older cet/redscript version

### ISSUE THREAD

**Issue by unk0wn-u53r** [MathiewMay/Street-Vendors#1]
Why only the up-to-date files from this mod and not the old one here? The latest doesn't work with older redscript or cet ... Where can I find them?

**Comment by MathiewMay** [comment]
Hi which version of the redscript do you need?

**Comment by MathiewMay** [comment]
Thanks i will be posting all the archive i still have in https://github.com/MathiewMay/Street-Vendors/releases/tag/Archive
